#!/bin/bash

: ${MAKESELF:=/usr/share/loki_setup/makeself}
: ${SETUPIMAGE:=/usr/share/loki_setup/image}

: ${VERSION:=0.0_`date +%Y%m%d%H%M`}
: ${RELEASE:=0}

set -e
set -x

arch=`uname -m`

rm -rf image
mkdir image

### loki-setup files
cp -a $SETUPIMAGE/{setup.data,setup.sh} image/

### splash
rm -f image/setup.data/splash.xpm
[ -e splash.xpm ] && cp splash.xpm image/setup.data/splash.xpm
rm -f image/quake3.png
cp ../quake3.png image/quake3.png

### binaries
src="../../../../../build"

mkdir image/tmp
pushd image/tmp
# 32 bit binaries
install -m 755 $src/release-linux-i386/wop-engine.i386 wop-engine.i386
install -m 755 $src/release-linux-i386/wopded.i386 wopded.i386
popd

tar --owner=root --group=root -C ./image/tmp -cf ./image/wop-engine.i386.tar .
rm -rf ./image/tmp

mkdir image/tmp
pushd image/tmp
# 64 bit binaries
install -m 755 $src/release-linux-x86_64/wop-engine.x86_64 wop-engine.x86_64
install -m 755 $src/release-linux-x86_64/wopded.x86_64 wopded.x86_64
popd

tar --owner=root --group=root -C ./image/tmp -cf ./image/wop-engine.x86_64.tar .
rm -rf image/tmp

mkdir image/tmp
pushd image/tmp
# ppc binaries
install -m 755 $src/release-linux-ppc/wop-engine.ppc wop-engine.ppc
install -m 755 $src/release-linux-ppc/wopded.ppc wopded.ppc
popd

tar --owner=root --group=root -C ./image/tmp -cf ./image/wop-engine.ppc.tar .
rm -rf image/tmp

# wop's pk3 files
install -m 644 ./wop-data.tar image/wop-data.tar

### setup.xml
sed 's/@VERSION@/'$VERSION'/g' < setup.xml > image/setup.data/setup.xml

### uninstall script
install -m 755 ./preuninstall.sh image/preuninstall.sh

### start script
mkdir -p image/bin/Linux/x86
mkdir -p image/bin/Linux/x86_64
mkdir -p image/bin/Linux/ppc

install -m 755 wop.sh image/bin/Linux/x86/WoP
install -m 755 wop.sh image/bin/Linux/x86_64/WoP
install -m 755 wop.sh image/bin/Linux/ppc/WoP

### README, COPYING and EULA
#install -m 644 ../../../COPYING.txt image/COPYING
#install -m 644 ./id_patch_pk3s_Q3A_EULA.txt image/id_patch_pk3s_Q3A_EULA.txt

### makeself installer
$MAKESELF/makeself.sh image wop-$VERSION-$RELEASE.run "ioquake3 $VERSION-$RELEASE" ./setup.sh
