#include "vk_postprocess.h"
#include "vk_fbo.h"
#include "vk_instance.h"
#include "vk_shaders.h"
#include "tr_cvar.h"
#include "ref_import.h"

// Shader SPIR-V (generated by build system)
extern unsigned char postprocess_vert_spv[];
extern int postprocess_vert_spv_size;
extern unsigned char greyscale_frag_spv[];
extern int greyscale_frag_spv_size;

static VkShaderModule s_postprocessVert = VK_NULL_HANDLE;
static VkShaderModule s_greyscaleFrag = VK_NULL_HANDLE;
static VkDescriptorSetLayout s_descriptorSetLayout = VK_NULL_HANDLE;
static VkPipelineLayout s_pipelineLayout = VK_NULL_HANDLE;
static VkPipeline s_greyscalePipeline = VK_NULL_HANDLE;
static VkRenderPass s_swapchainRenderPass = VK_NULL_HANDLE;
static VkDescriptorPool s_descriptorPool = VK_NULL_HANDLE;
static VkDescriptorSet s_descriptorSet = VK_NULL_HANDLE;
static VkSampler s_sampler = VK_NULL_HANDLE;
static VkFramebuffer s_swapchainFramebuffers[MAX_SWAPCHAIN_IMAGES];

static void createSwapchainRenderPass(void) {
	VkAttachmentDescription attachment = {0};
	VkAttachmentReference colorRef;
	VkSubpassDescription subpass = {0};
	VkRenderPassCreateInfo rpInfo = {0};

	attachment.format = vk.surface_format.format;
	attachment.samples = VK_SAMPLE_COUNT_1_BIT;
	attachment.loadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
	attachment.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
	attachment.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
	attachment.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	attachment.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	attachment.finalLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;

	colorRef.attachment = 0;
	colorRef.layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

	subpass.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
	subpass.colorAttachmentCount = 1;
	subpass.pColorAttachments = &colorRef;

	rpInfo.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
	rpInfo.attachmentCount = 1;
	rpInfo.pAttachments = &attachment;
	rpInfo.subpassCount = 1;
	rpInfo.pSubpasses = &subpass;

	VK_CHECK(qvkCreateRenderPass(vk.device, &rpInfo, NULL, &s_swapchainRenderPass));
}

static void createSwapchainFramebuffers(void) {
	uint32_t i;
	for (i = 0; i < vk.swapchain_image_count; i++) {
		VkFramebufferCreateInfo fbInfo = {0};
		fbInfo.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
		fbInfo.renderPass = s_swapchainRenderPass;
		fbInfo.attachmentCount = 1;
		fbInfo.pAttachments = &vk.swapchain_image_views[i];
		fbInfo.width = vk.surface_caps.currentExtent.width;
		fbInfo.height = vk.surface_caps.currentExtent.height;
		fbInfo.layers = 1;
		VK_CHECK(qvkCreateFramebuffer(vk.device, &fbInfo, NULL, &s_swapchainFramebuffers[i]));
	}
}

static void createPipeline(void) {
	VkPipelineShaderStageCreateInfo stages[2] = {{0}, {0}};
	VkPipelineVertexInputStateCreateInfo vertexInput = {0};
	VkPipelineInputAssemblyStateCreateInfo inputAssembly = {0};
	VkPipelineViewportStateCreateInfo viewportState = {0};
	VkPipelineRasterizationStateCreateInfo rasterizer = {0};
	VkPipelineMultisampleStateCreateInfo multisampling = {0};
	VkPipelineColorBlendAttachmentState blendAttachment = {0};
	VkPipelineColorBlendStateCreateInfo colorBlending = {0};
	VkPipelineDynamicStateCreateInfo dynamicState = {0};
	VkDynamicState dynStates[] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
	VkGraphicsPipelineCreateInfo pipelineInfo = {0};
	VkViewport viewport = {0};
	VkRect2D scissor = {0};

	stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
	stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
	stages[0].module = s_postprocessVert;
	stages[0].pName = "main";

	stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
	stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
	stages[1].module = s_greyscaleFrag;
	stages[1].pName = "main";

	vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
	// No vertex input - fullscreen triangle generated in shader

	inputAssembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
	inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

	viewport.width = (float)vk.surface_caps.currentExtent.width;
	viewport.height = (float)vk.surface_caps.currentExtent.height;
	viewport.maxDepth = 1.0f;
	scissor.extent = vk.surface_caps.currentExtent;

	viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
	viewportState.viewportCount = 1;
	viewportState.pViewports = &viewport;
	viewportState.scissorCount = 1;
	viewportState.pScissors = &scissor;

	rasterizer.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
	rasterizer.polygonMode = VK_POLYGON_MODE_FILL;
	rasterizer.lineWidth = 1.0f;
	rasterizer.cullMode = VK_CULL_MODE_NONE;
	rasterizer.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;

	multisampling.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
	multisampling.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

	blendAttachment.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
									 VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;

	colorBlending.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
	colorBlending.attachmentCount = 1;
	colorBlending.pAttachments = &blendAttachment;

	dynamicState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
	dynamicState.dynamicStateCount = 2;
	dynamicState.pDynamicStates = dynStates;

	pipelineInfo.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
	pipelineInfo.stageCount = 2;
	pipelineInfo.pStages = stages;
	pipelineInfo.pVertexInputState = &vertexInput;
	pipelineInfo.pInputAssemblyState = &inputAssembly;
	pipelineInfo.pViewportState = &viewportState;
	pipelineInfo.pRasterizationState = &rasterizer;
	pipelineInfo.pMultisampleState = &multisampling;
	pipelineInfo.pColorBlendState = &colorBlending;
	pipelineInfo.pDynamicState = &dynamicState;
	pipelineInfo.layout = s_pipelineLayout;
	pipelineInfo.renderPass = s_swapchainRenderPass;
	pipelineInfo.subpass = 0;

	VK_CHECK(qvkCreateGraphicsPipelines(vk.device, VK_NULL_HANDLE, 1, &pipelineInfo, NULL, &s_greyscalePipeline));
}

void VK_PostProcess_Init(void) {
	VkShaderModuleCreateInfo moduleInfo = {0};
	VkDescriptorSetLayoutBinding binding = {0};
	VkDescriptorSetLayoutCreateInfo layoutInfo = {0};
	VkPushConstantRange pushRange;
	VkPipelineLayoutCreateInfo plInfo = {0};
	VkDescriptorPoolSize poolSize;
	VkDescriptorPoolCreateInfo poolInfo = {0};
	VkDescriptorSetAllocateInfo allocInfo = {0};
	VkSamplerCreateInfo samplerInfo = {0};
	VkDescriptorImageInfo imageInfo = {0};
	VkWriteDescriptorSet write = {0};
	vk_fbo_t *mainFBO;

	ri.Printf(PRINT_ALL, "VK_PostProcess_Init\n");

	// Load shader modules
	moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
	moduleInfo.codeSize = postprocess_vert_spv_size;
	moduleInfo.pCode = (const uint32_t *)postprocess_vert_spv;
	VK_CHECK(qvkCreateShaderModule(vk.device, &moduleInfo, NULL, &s_postprocessVert));

	moduleInfo.codeSize = greyscale_frag_spv_size;
	moduleInfo.pCode = (const uint32_t *)greyscale_frag_spv;
	VK_CHECK(qvkCreateShaderModule(vk.device, &moduleInfo, NULL, &s_greyscaleFrag));

	// Descriptor set layout: one combined image sampler
	binding.binding = 0;
	binding.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
	binding.descriptorCount = 1;
	binding.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;

	layoutInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
	layoutInfo.bindingCount = 1;
	layoutInfo.pBindings = &binding;
	VK_CHECK(qvkCreateDescriptorSetLayout(vk.device, &layoutInfo, NULL, &s_descriptorSetLayout));

	// Pipeline layout: descriptor set + push constant for greyscale value
	pushRange.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
	pushRange.offset = 0;
	pushRange.size = sizeof(float);

	plInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
	plInfo.setLayoutCount = 1;
	plInfo.pSetLayouts = &s_descriptorSetLayout;
	plInfo.pushConstantRangeCount = 1;
	plInfo.pPushConstantRanges = &pushRange;
	VK_CHECK(qvkCreatePipelineLayout(vk.device, &plInfo, NULL, &s_pipelineLayout));

	// Descriptor pool and set
	poolSize.type = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
	poolSize.descriptorCount = 1;

	poolInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
	poolInfo.maxSets = 1;
	poolInfo.poolSizeCount = 1;
	poolInfo.pPoolSizes = &poolSize;
	VK_CHECK(qvkCreateDescriptorPool(vk.device, &poolInfo, NULL, &s_descriptorPool));

	allocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
	allocInfo.descriptorPool = s_descriptorPool;
	allocInfo.descriptorSetCount = 1;
	allocInfo.pSetLayouts = &s_descriptorSetLayout;
	VK_CHECK(qvkAllocateDescriptorSets(vk.device, &allocInfo, &s_descriptorSet));

	// Sampler for FBO color
	samplerInfo.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
	samplerInfo.magFilter = VK_FILTER_LINEAR;
	samplerInfo.minFilter = VK_FILTER_LINEAR;
	samplerInfo.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
	samplerInfo.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
	samplerInfo.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
	VK_CHECK(qvkCreateSampler(vk.device, &samplerInfo, NULL, &s_sampler));

	// Update descriptor set to point to main FBO color
	mainFBO = VK_FBO_GetMain();
	imageInfo.sampler = s_sampler;
	imageInfo.imageView = mainFBO->colorView;
	imageInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;

	write.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
	write.dstSet = s_descriptorSet;
	write.dstBinding = 0;
	write.descriptorCount = 1;
	write.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
	write.pImageInfo = &imageInfo;
	qvkUpdateDescriptorSets(vk.device, 1, &write, 0, NULL);

	// Render pass and framebuffers for swapchain output
	createSwapchainRenderPass();
	createSwapchainFramebuffers();

	// Pipeline
	createPipeline();
}

void VK_PostProcess_Shutdown(void) {
	uint32_t i;

	if (s_greyscalePipeline != VK_NULL_HANDLE)
		qvkDestroyPipeline(vk.device, s_greyscalePipeline, NULL);
	if (s_pipelineLayout != VK_NULL_HANDLE)
		qvkDestroyPipelineLayout(vk.device, s_pipelineLayout, NULL);
	if (s_descriptorSetLayout != VK_NULL_HANDLE)
		qvkDestroyDescriptorSetLayout(vk.device, s_descriptorSetLayout, NULL);
	if (s_descriptorPool != VK_NULL_HANDLE)
		qvkDestroyDescriptorPool(vk.device, s_descriptorPool, NULL);
	if (s_sampler != VK_NULL_HANDLE)
		qvkDestroySampler(vk.device, s_sampler, NULL);
	if (s_postprocessVert != VK_NULL_HANDLE)
		qvkDestroyShaderModule(vk.device, s_postprocessVert, NULL);
	if (s_greyscaleFrag != VK_NULL_HANDLE)
		qvkDestroyShaderModule(vk.device, s_greyscaleFrag, NULL);
	if (s_swapchainRenderPass != VK_NULL_HANDLE)
		qvkDestroyRenderPass(vk.device, s_swapchainRenderPass, NULL);
	for (i = 0; i < vk.swapchain_image_count; i++) {
		if (s_swapchainFramebuffers[i] != VK_NULL_HANDLE)
			qvkDestroyFramebuffer(vk.device, s_swapchainFramebuffers[i], NULL);
	}

	s_greyscalePipeline = VK_NULL_HANDLE;
	s_pipelineLayout = VK_NULL_HANDLE;
	s_descriptorSetLayout = VK_NULL_HANDLE;
	s_descriptorPool = VK_NULL_HANDLE;
	s_sampler = VK_NULL_HANDLE;
	s_postprocessVert = VK_NULL_HANDLE;
	s_greyscaleFrag = VK_NULL_HANDLE;
	s_swapchainRenderPass = VK_NULL_HANDLE;
	memset(s_swapchainFramebuffers, 0, sizeof(s_swapchainFramebuffers));
}

qboolean VK_PostProcess_Render(VkCommandBuffer cmdBuf, uint32_t swapchainIdx) {
	float greyscale;
	VkRenderPassBeginInfo rpBegin = {0};
	VkViewport viewport;
	VkRect2D scissor;

	greyscale = r_greyscale->value;
	if (greyscale <= 0.0f)
		return qfalse;
	if (greyscale > 1.0f)
		greyscale = 1.0f;

	rpBegin.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
	rpBegin.renderPass = s_swapchainRenderPass;
	rpBegin.framebuffer = s_swapchainFramebuffers[swapchainIdx];
	rpBegin.renderArea.extent = vk.surface_caps.currentExtent;

	qvkCmdBeginRenderPass(cmdBuf, &rpBegin, VK_SUBPASS_CONTENTS_INLINE);

	qvkCmdBindPipeline(cmdBuf, VK_PIPELINE_BIND_POINT_GRAPHICS, s_greyscalePipeline);
	qvkCmdBindDescriptorSets(cmdBuf, VK_PIPELINE_BIND_POINT_GRAPHICS, s_pipelineLayout, 0, 1, &s_descriptorSet, 0, NULL);
	qvkCmdPushConstants(cmdBuf, s_pipelineLayout, VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(float), &greyscale);

	viewport.x = 0;
	viewport.y = 0;
	viewport.width = (float)vk.surface_caps.currentExtent.width;
	viewport.height = (float)vk.surface_caps.currentExtent.height;
	viewport.minDepth = 0.0f;
	viewport.maxDepth = 1.0f;
	qvkCmdSetViewport(cmdBuf, 0, 1, &viewport);

	scissor.offset.x = 0;
	scissor.offset.y = 0;
	scissor.extent = vk.surface_caps.currentExtent;
	qvkCmdSetScissor(cmdBuf, 0, 1, &scissor);

	// Draw fullscreen triangle (3 vertices, no vertex buffer)
	qvkCmdDraw(cmdBuf, 3, 1, 0, 0);

	qvkCmdEndRenderPass(cmdBuf);

	return qtrue;
}
