// Custom shader file for wop_diner.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

wop_diner/C0B1521B369240DCA02849A4A7478C0E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/pad_harm/sitzbank01b_white2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/C63A5073ADFFF5ACCD914A78E9C1833B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/CCE17D6C46074B172BB70C34F3F4B59F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/D3EB59F87D259AE6D2A7A2A3ED0FFBD9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/musicbox_front.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/ADCF426F021EDA8B788DF79907D8BFBD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/4A28260D1B5D99AF0BC1ED49A3C67846
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/85E46B8870AEA94AC25B873D6F0AADAD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/pad_wood/wood019a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/9B24CAF9C1949F08ADFE5CAC223FDD41
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/5A3E83AD0FDEF9124F5714892C3EF126
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/metalline01b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/FA5E67CC6CFA62CF974C21B4077E879E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/616019306E6410440B6B31A061569E59
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/pad_harm/sitzbank01b_white2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/8B52C55D4692FEF9E96E5B6C6141E76B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/770FB59977580A71B5EF7D257FBAD77F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/musicbox_front.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/F3D7384E73CFA011655A609CACF1F128
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/1075F04F1CA28B8D860DEEE40D371D98
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/786770417E14BD8E7CCBA851910AD303
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/6930C0A374DF8AAC1126CA118F84CE73
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wallin/color32.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

