// Custom shader file for wop_dinerBB.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

wop_dinerBB/73666EB0C2CF8B408755B1B321908BBE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0004
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/sitzbank01b_white2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/FA2AA1D4C06A313C6D56282F5D7C8B5C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/32A7EA3E3BE65C22737B5826B98C1E6D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/CEBF3BC23BF6DE2A5357F95C558ED68E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0002
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/E36377B5DB63EB32A015811D5F19AE77
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0002
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/599C3F7A60001E2643ADC71948AC5432
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.01563
	}

	{
		map textures/pad_tex/col13
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/FE0A9852BD4F9CA60374DFA304B17B2F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/5697DAA32CC15DE50BAB541221CBC442
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/metalline01b
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/AB353D44F0E51CE86073EA7634732C24
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/87842D0851BBB39352BEBF45B6E551AB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/sitzbank01b_white2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/7F7075E94BF4F63676BEF48899B30716
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0012
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/6D17E39126424A2B1B673010E349AEFD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.07031 -0.38281
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/204EC5BE0221871F4F6A64E8444C7099
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/85E46B8870AEA94AC25B873D6F0AADAD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/B61EF35C24D8F476FB452CD1BB6831A3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0004
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/metalline01b
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/C6D26806D24E8C78AF839A25BAD1444A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/AC0BAF0352478A05AD1B9F3F0E7EA5D1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0013
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/704D757D7FD162AAA4CA6A70BF410D16
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/BC43BFD47357D35950C5BCF92F0F1AAB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

