// Custom shader file for wop_dinerBB.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

wop_dinerBB/B611A673C803C59F4667C56491997A4B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.45313 0.10938
	}

	{
		map textures/pad_harm/sitzbank01b_white2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/32A7EA3E3BE65C22737B5826B98C1E6D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/DC04DA76CD2321B81A5538F754E56C84
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/25D25655530F2E12DA2440933C41F3B5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/FE0A9852BD4F9CA60374DFA304B17B2F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/5651E6EF702DF1BBCE508DF7EC93B60D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0002
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/metalline01b
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/73666EB0C2CF8B408755B1B321908BBE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0004
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/sitzbank01b_white2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/F3D2A53FC41ED309C0060609282F06DC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0007
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/8AE756171F8382B448B29289FE8276AF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/CEBF3BC23BF6DE2A5357F95C558ED68E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0002
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/E36377B5DB63EB32A015811D5F19AE77
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0002
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/B23B4B85E20CDD394FD2DA508C158415
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0007
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/5697DAA32CC15DE50BAB541221CBC442
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/metalline01b
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/FE361E195E08AEA7D95AB512D23EA346
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}

	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0000
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

