// Custom shader file for wop_diner.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

wop_diner/A4CD88E2E57E2BDF4762EA39A4287872
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/sitzbank01b_white2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/C63A5073ADFFF5ACCD914A78E9C1833B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0010
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/330BCFB1EFD5CEB669157B90FEC25931
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/DA7928307F67AECEEC387CD04C649F86
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/0B4ED52144B4B6B51C8A0A75B777EFD2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/5507B52E5F573D2225377552919FCE36
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_tex/col13
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/311EA3D5D540CD20966FB74FC3D99B55
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0013
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/6A709F29FBF55784E9478336AC089514
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0012
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/DF365955E9FDF18A784C2DBF5F4DF09A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/metalline01b
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/AC46AD7EF9B0B24A9299C9336588F372
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0013
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/CCE17D6C46074B172BB70C34F3F4B59F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0011
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/73FF178185DD8AFD36359A2B0D7B59C8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/sitzbank01b_white2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/F5BA620AAD6CC7FD8EC4D9C058B4ECA1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/0A7BE88CE6BEEE80425F26EBE2D33D20
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0015
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/BD9E6F8F8EF3982CB6717847807783C2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/musicbox_front
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/A9F7DFE2387AC91D791C0BF66CC4C799
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0013
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_tex/col13
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/23992626657480F3EB973B0FA0B3E3D0
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0018
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/FBCE5B76A1D723E33EDB235D475DB21E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.07031 0.00000
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/AB353D44F0E51CE86073EA7634732C24
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/F36B83960361F9B77E7025B628EFCB8E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0017
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/1385F064D1B98B9C96CD359BC44C6798
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0018
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/9CBBE51B36E392181EB4681A7613C359
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

