// Custom shader file for wop_dinerBB.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

wop_dinerBB/B1BF797C5F0EA6E16A87B90B75FBE43B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0006
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/sitzbank01b_white2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/DA5FE4FA0F9730FC0EA950D426550988
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0011
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/A81B9ECD804A8B86F5E57FC1520FD5BB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0010
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/DC04DA76CD2321B81A5538F754E56C84
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/25D25655530F2E12DA2440933C41F3B5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/47438478A660622E90AC4168DB90621E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_tex/col13
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/DA7C1F3D162CFF76BF94D7BC0729088B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0013
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/04C0B811EBFB6A89F82C81D9772EB9E1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0011
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/81CE264A0EF960C57F3F9E5AAD48B784
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/pad_harm/metalline01b
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/AB353D44F0E51CE86073EA7634732C24
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/7F7075E94BF4F63676BEF48899B30716
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0012
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/616019306E6410440B6B31A061569E59
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/pad_harm/sitzbank01b_white2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/F4C1D4B7914A1C2FA5E7407999F41E63
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0015
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/9F148D40C2B11C5D7E25FAC27067D952
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0013
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/BCE1402B532D6BFE27D361B030326339
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0010
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_tex/col13
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/A3788F388C0EACE316D276861A437451
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0015
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_dinerBB/204EC5BE0221871F4F6A64E8444C7099
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_dinerBB/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

