// Custom shader file for wop_diner.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

wop_diner/1AA5F81C7F336A4AC513E064531DD845
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0005
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/sitzbank01b_white2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/C63A5073ADFFF5ACCD914A78E9C1833B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0010
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/94749B9E68A1F9BD6AE49F3570AC6085
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0012
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/770FB59977580A71B5EF7D257FBAD77F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/musicbox_front
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/ADCF426F021EDA8B788DF79907D8BFBD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0001
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/4A28260D1B5D99AF0BC1ED49A3C67846
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0001
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/dinerground
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/599C3F7A60001E2643ADC71948AC5432
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.01563
	}

	{
		map textures/pad_tex/col13
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/3F10C77D9F20ABEB0A3482BD7B4EC19A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/F995F6DAD475E6F99FA6BF0110BA7D07
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03906 0.00000
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/FE7C5E96531CB9F1D6513CB433B20A47
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0002
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/metalline01b
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/AC46AD7EF9B0B24A9299C9336588F372
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0013
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/8B52C55D4692FEF9E96E5B6C6141E76B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0009
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/1075F04F1CA28B8D860DEEE40D371D98
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/73FF178185DD8AFD36359A2B0D7B59C8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0008
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/sitzbank01b_white2
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/D3EB59F87D259AE6D2A7A2A3ED0FFBD9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0004
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/musicbox_front
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/C29BAB6708849E37A60D36D798296970
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/pad_wood/wood019a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/5A3E83AD0FDEF9124F5714892C3EF126
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0003
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_harm/metalline01b
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/F5BA620AAD6CC7FD8EC4D9C058B4ECA1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0014
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

wop_diner/FA5E67CC6CFA62CF974C21B4077E879E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/wop_diner/lm_0004
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 1
		tcGen lightmap
	}

	{
		map textures/pad_wood/wood026a
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

