#include "chars.h"
skill 1
{
	CHARACTERISTIC_NAME							"padlilly"
	CHARACTERISTIC_GENDER						"Female"
	CHARACTERISTIC_ATTACK_SKILL					0.250
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/padlilly_w.c"
	CHARACTERISTIC_AIM_SKILL					0.250
	CHARACTERISTIC_AIM_ACCURACY					0.150
	CHARACTERISTIC_VIEW_FACTOR					0.250
	CHARACTERISTIC_VIEW_MAXCHANGE				90
	CHARACTERISTIC_REACTIONTIME					3.00

	CHARACTERISTIC_CHAT_FILE					"bots/girls_t.c"
	CHARACTERISTIC_CHAT_NAME					"padgirl"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.500
	CHARACTERISTIC_CHAT_MISC					0.500
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.500
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.500
	CHARACTERISTIC_CHAT_KILL					0.500
	CHARACTERISTIC_CHAT_DEATH					0.500
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.500
	CHARACTERISTIC_CHAT_HITTALKING				0.100
	CHARACTERISTIC_CHAT_HITNODEATH				0.500
	CHARACTERISTIC_CHAT_HITNOKILL				0.500
	CHARACTERISTIC_CHAT_RANDOM					0.500
	CHARACTERISTIC_CHAT_REPLY					0.500

	CHARACTERISTIC_CROUCHER						0.000
	CHARACTERISTIC_JUMPER						0.000
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				0.500
	CHARACTERISTIC_GRAPPLE_USER					0.500

	CHARACTERISTIC_ITEMWEIGHTS					"fw_items.c"
	CHARACTERISTIC_AGGRESSION					0.250
	CHARACTERISTIC_SELFPRESERVATION				0.500
	CHARACTERISTIC_VENGEFULNESS					0.250

	CHARACTERISTIC_EASY_FRAGGER					0.500
	CHARACTERISTIC_ALERTNESS					0.01
	CHARACTERISTIC_SPRAYLOGO					"18_niceguy"
}

skill 4
{
	CHARACTERISTIC_NAME							"padlilly"
	CHARACTERISTIC_GENDER						"Female"
	CHARACTERISTIC_ATTACK_SKILL					0.800
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/padlilly_w.c"
	CHARACTERISTIC_AIM_SKILL					0.900
	CHARACTERISTIC_AIM_ACCURACY					0.550
	CHARACTERISTIC_VIEW_FACTOR					0.900
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_REACTIONTIME					1.75

	CHARACTERISTIC_CHAT_FILE					"bots/girls_t.c"
	CHARACTERISTIC_CHAT_NAME					"padgirl"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.100
	CHARACTERISTIC_CHAT_MISC					0.100
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.100
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.100
	CHARACTERISTIC_CHAT_KILL					0.100
	CHARACTERISTIC_CHAT_DEATH					0.100
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.100
	CHARACTERISTIC_CHAT_HITTALKING				0.100
	CHARACTERISTIC_CHAT_HITNODEATH				0.100
	CHARACTERISTIC_CHAT_HITNOKILL				0.100
	CHARACTERISTIC_CHAT_RANDOM					0.100
	CHARACTERISTIC_CHAT_REPLY					0.100

	CHARACTERISTIC_CROUCHER						0.100
	CHARACTERISTIC_JUMPER						1.000
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				1.000
	CHARACTERISTIC_GRAPPLE_USER					1.000

	CHARACTERISTIC_ITEMWEIGHTS					"fw_items.c"
	CHARACTERISTIC_AGGRESSION					1.000
	CHARACTERISTIC_SELFPRESERVATION				1.000
	CHARACTERISTIC_VENGEFULNESS					1.000

	CHARACTERISTIC_EASY_FRAGGER					1.000
	CHARACTERISTIC_ALERTNESS					0.05
	CHARACTERISTIC_SPRAYLOGO					"18_niceguy"
}

skill 5
{
	CHARACTERISTIC_NAME							"padlilly"
	CHARACTERISTIC_GENDER						"Female"
	CHARACTERISTIC_ATTACK_SKILL					1.000
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/padlilly_w.c"
	CHARACTERISTIC_AIM_SKILL					1.000
	CHARACTERISTIC_AIM_ACCURACY					1.000
	CHARACTERISTIC_VIEW_FACTOR					1.000
	CHARACTERISTIC_VIEW_MAXCHANGE				360
	CHARACTERISTIC_REACTIONTIME					0.00

	CHARACTERISTIC_CHAT_FILE					"bots/girls_t.c"
	CHARACTERISTIC_CHAT_NAME					"padgirl"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.100
	CHARACTERISTIC_CHAT_MISC					0.100
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.100
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.100
	CHARACTERISTIC_CHAT_KILL					0.100
	CHARACTERISTIC_CHAT_DEATH					0.100
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.100
	CHARACTERISTIC_CHAT_HITTALKING				0.100
	CHARACTERISTIC_CHAT_HITNODEATH				0.100
	CHARACTERISTIC_CHAT_HITNOKILL				0.100
	CHARACTERISTIC_CHAT_RANDOM					0.100
	CHARACTERISTIC_CHAT_REPLY					0.100

	CHARACTERISTIC_CROUCHER						0.000
	CHARACTERISTIC_JUMPER						1.000
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				1.000
	CHARACTERISTIC_GRAPPLE_USER					1.000

	CHARACTERISTIC_ITEMWEIGHTS					"fw_items.c"
	CHARACTERISTIC_AGGRESSION					1.000
	CHARACTERISTIC_SELFPRESERVATION				1.000
	CHARACTERISTIC_VENGEFULNESS					1.000

	CHARACTERISTIC_EASY_FRAGGER					1.000
	CHARACTERISTIC_ALERTNESS					0.100
	CHARACTERISTIC_SPRAYLOGO					"18_niceguy"
}
