// Programmer:		tone (abell@iname.com)
#include "chars.h"


skill 1{
	CHARACTERISTIC_NAME							"PADMAN"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.5
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/padman_w.c"
	CHARACTERISTIC_AIM_SKILL					0.10
	CHARACTERISTIC_AIM_ACCURACY					0.10
	CHARACTERISTIC_VIEW_FACTOR					0.50
	CHARACTERISTIC_VIEW_MAXCHANGE				180
	CHARACTERISTIC_REACTIONTIME					1.0

	CHARACTERISTIC_CHAT_FILE					"bots/guys_t.c"
	CHARACTERISTIC_CHAT_NAME					"padman"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.45
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.525

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						1.0
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				0.75
	CHARACTERISTIC_GRAPPLE_USER					0.5

	CHARACTERISTIC_ITEMWEIGHTS					"fw_items.c"
	CHARACTERISTIC_AGGRESSION					0.75
	CHARACTERISTIC_SELFPRESERVATION				0.75
	CHARACTERISTIC_VENGEFULNESS					0.75

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.01

	CHARACTERISTIC_AIM_ACCURACY_NIPPER			0.15
	CHARACTERISTIC_AIM_ACCURACY_PUMPER			0.15
	CHARACTERISTIC_AIM_ACCURACY_BETTY			0.15
	CHARACTERISTIC_AIM_ACCURACY_BALLOONY		0.15
	CHARACTERISTIC_AIM_ACCURACY_BOASTER			0.15
	CHARACTERISTIC_AIM_ACCURACY_BUBBLEG			0.15
	CHARACTERISTIC_AIM_ACCURACY_SPLASHER		0.15
	CHARACTERISTIC_AIM_ACCURACY_IMPERIUS		0.15
	CHARACTERISTIC_AIM_SKILL_BETTY				0.15
	CHARACTERISTIC_AIM_SKILL_BALLOONY			0.15
	CHARACTERISTIC_AIM_SKILL_BUBBLEG			0.15
	CHARACTERISTIC_AIM_SKILL_IMPERIUS			0.15

	CHARACTERISTIC_FIRETHROTTLE					0.3
	CHARACTERISTIC_SPRAYLOGO					"15_padlogo"
}

skill 4{
	CHARACTERISTIC_NAME							"PADMAN"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.75
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/padman_w.c"
	CHARACTERISTIC_AIM_SKILL					0.85
	CHARACTERISTIC_AIM_ACCURACY					0.55
	CHARACTERISTIC_VIEW_FACTOR					0.85
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_REACTIONTIME					0.5

	CHARACTERISTIC_CHAT_FILE					"bots/guys_t.c"
	CHARACTERISTIC_CHAT_NAME					"padman"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.45
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.3

	CHARACTERISTIC_CROUCHER						0.05
	CHARACTERISTIC_JUMPER						1.0
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				0.75
	CHARACTERISTIC_GRAPPLE_USER					0.5

	CHARACTERISTIC_ITEMWEIGHTS					"fw_items.c"
	CHARACTERISTIC_AGGRESSION					0.75
	CHARACTERISTIC_SELFPRESERVATION				0.25
	CHARACTERISTIC_VENGEFULNESS					0.5

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.05

	CHARACTERISTIC_AIM_ACCURACY_NIPPER			0.600
	CHARACTERISTIC_AIM_ACCURACY_PUMPER			0.600
	CHARACTERISTIC_AIM_ACCURACY_BETTY			0.600
	CHARACTERISTIC_AIM_ACCURACY_BALLOONY		0.600
	CHARACTERISTIC_AIM_ACCURACY_BOASTER			0.600
	CHARACTERISTIC_AIM_ACCURACY_BUBBLEG			0.600
	CHARACTERISTIC_AIM_ACCURACY_SPLASHER		0.600
	CHARACTERISTIC_AIM_ACCURACY_IMPERIUS		0.600
	CHARACTERISTIC_AIM_SKILL_BETTY				0.600
	CHARACTERISTIC_AIM_SKILL_BALLOONY			0.600
	CHARACTERISTIC_AIM_SKILL_BUBBLEG			0.600
	CHARACTERISTIC_AIM_SKILL_IMPERIUS			0.600

	CHARACTERISTIC_FIRETHROTTLE					1.0
	CHARACTERISTIC_SPRAYLOGO					"15_padlogo"
}

skill 5{
	CHARACTERISTIC_NAME							"PADMAN"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.95
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/padman_w.c"
	CHARACTERISTIC_AIM_SKILL					0.9
	CHARACTERISTIC_AIM_ACCURACY					0.7
	CHARACTERISTIC_VIEW_FACTOR					0.85
	CHARACTERISTIC_VIEW_MAXCHANGE				240
	CHARACTERISTIC_REACTIONTIME					0.1

	CHARACTERISTIC_CHAT_FILE					"bots/guys_t.c"
	CHARACTERISTIC_CHAT_NAME					"padman"
	CHARACTERISTIC_CHAT_CPM						400
	CHARACTERISTIC_CHAT_INSULT					0.45
	CHARACTERISTIC_CHAT_MISC					0.5
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.5
	CHARACTERISTIC_CHAT_HITTALKING				0.15
	CHARACTERISTIC_CHAT_HITNODEATH				0.5
	CHARACTERISTIC_CHAT_HITNOKILL				0.5
	CHARACTERISTIC_CHAT_RANDOM					0.5
	CHARACTERISTIC_CHAT_REPLY					0.1

	CHARACTERISTIC_CROUCHER						0.05
	CHARACTERISTIC_JUMPER						0.5
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				0.75
	CHARACTERISTIC_GRAPPLE_USER					0.5

	CHARACTERISTIC_ITEMWEIGHTS					"fw_items.c"
	CHARACTERISTIC_AGGRESSION					0.75
	CHARACTERISTIC_SELFPRESERVATION				0.25
	CHARACTERISTIC_VENGEFULNESS					0.5

	CHARACTERISTIC_EASY_FRAGGER					0.5
	CHARACTERISTIC_ALERTNESS					0.1

	CHARACTERISTIC_AIM_ACCURACY_NIPPER			0.900
	CHARACTERISTIC_AIM_ACCURACY_PUMPER			0.900
	CHARACTERISTIC_AIM_ACCURACY_BETTY			0.900
	CHARACTERISTIC_AIM_ACCURACY_BALLOONY		0.900
	CHARACTERISTIC_AIM_ACCURACY_BOASTER			0.900
	CHARACTERISTIC_AIM_ACCURACY_BUBBLEG			0.900
	CHARACTERISTIC_AIM_ACCURACY_SPLASHER		0.900
	CHARACTERISTIC_AIM_ACCURACY_IMPERIUS		0.900
	CHARACTERISTIC_AIM_SKILL_BETTY				0.900
	CHARACTERISTIC_AIM_SKILL_BALLOONY			0.900
	CHARACTERISTIC_AIM_SKILL_BUBBLEG			0.900
	CHARACTERISTIC_AIM_SKILL_IMPERIUS			0.900

	CHARACTERISTIC_FIRETHROTTLE					1.0
	CHARACTERISTIC_SPRAYLOGO					"15_padlogo"
}
