// Generated by Quake 3 Bot Designer

//===========================================================================
// Name:			padgirl_i.c
// Function:		weapon weights for padgirl
// Programmer:		Q3BD
// Last update:		Saturday, January 26, 2002 at 14:24:06
//===========================================================================


#include "inv.h"

/*
//initial health/armor states
#define FS_HEALTH				1
#define FS_ARMOR				2

//initial weapon weights
#define W_SHOTGUN				500
#define W_MACHINEGUN			70
#define W_GRENADELAUNCHER		140
#define W_ROCKETLAUNCHER		320
#define W_RAILGUN				85
#define W_BFG10K				30
#define W_LIGHTNING				50
#define W_PLASMAGUN				100

//the bot has the weapons, so the weights change a little bit
#define GWW_SHOTGUN				350
#define GWW_MACHINEGUN			50
#define GWW_GRENADELAUNCHER		130
#define GWW_ROCKETLAUNCHER		290
#define GWW_RAILGUN				25
#define GWW_BFG10K				41
#define GWW_LIGHTNING			40
#define GWW_PLASMAGUN			100

//initial powerup weights
#define W_PADPOWER				400
#define W_CLIMBER				100
#define W_SPEEDY				280
#define W_JUMPER				80
#define W_VISIONLESS			230
#define W_REVIVAL				180
#define W_FLOATER				 80
#define W_KILLERDUCKS			250

//flag weight
#define FLAG_WEIGHT				50
*/
//
#include "fw_items.c"
