//	By: milla, milla@chiq.net, http://www.chiq.net
#include "chars.h"

skill 1{
	CHARACTERISTIC_NAME							"Pelvis"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.2
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/pelvis_w.c"
	CHARACTERISTIC_AIM_SKILL					0.2
	CHARACTERISTIC_AIM_ACCURACY					0.15
	CHARACTERISTIC_VIEW_FACTOR					0.1
	CHARACTERISTIC_VIEW_MAXCHANGE				40
	CHARACTERISTIC_REACTIONTIME					1.5

	CHARACTERISTIC_CHAT_FILE					"bots/guys_t.c"
	CHARACTERISTIC_CHAT_NAME					"padman"
	CHARACTERISTIC_CHAT_CPM						225
	CHARACTERISTIC_CHAT_INSULT					0.8
	CHARACTERISTIC_CHAT_MISC					0.8
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.3
	CHARACTERISTIC_CHAT_HITTALKING				0.2
	CHARACTERISTIC_CHAT_HITNODEATH				0.8
	CHARACTERISTIC_CHAT_HITNOKILL				0.65
	CHARACTERISTIC_CHAT_RANDOM					0.7
	CHARACTERISTIC_CHAT_REPLY					0.5

	CHARACTERISTIC_CROUCHER						0.1
	CHARACTERISTIC_JUMPER						0.4
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				0.3
	CHARACTERISTIC_GRAPPLE_USER					0.1

	CHARACTERISTIC_ITEMWEIGHTS					"fw_items.c"
	CHARACTERISTIC_AGGRESSION					0.7
	CHARACTERISTIC_SELFPRESERVATION				0.5
	CHARACTERISTIC_VENGEFULNESS					0.5

	CHARACTERISTIC_EASY_FRAGGER					0.15
	CHARACTERISTIC_ALERTNESS					0.01
	CHARACTERISTIC_SPRAYLOGO					"03_smile"
}

skill 4{
	CHARACTERISTIC_NAME							"Pelvis"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.8
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/pelvis_w.c"
	CHARACTERISTIC_AIM_SKILL					0.8
	CHARACTERISTIC_AIM_ACCURACY					0.55
	CHARACTERISTIC_VIEW_FACTOR					0.3
	CHARACTERISTIC_VIEW_MAXCHANGE				80
	CHARACTERISTIC_REACTIONTIME					0.5

	CHARACTERISTIC_CHAT_FILE					"bots/guys_t.c"
	CHARACTERISTIC_CHAT_NAME					"padman"
	CHARACTERISTIC_CHAT_CPM						225
	CHARACTERISTIC_CHAT_INSULT					0.8
	CHARACTERISTIC_CHAT_MISC					0.8
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.3
	CHARACTERISTIC_CHAT_HITTALKING				0.2
	CHARACTERISTIC_CHAT_HITNODEATH				0.8
	CHARACTERISTIC_CHAT_HITNOKILL				0.65
	CHARACTERISTIC_CHAT_RANDOM					0.7
	CHARACTERISTIC_CHAT_REPLY					0.5

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.55
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				0.45
	CHARACTERISTIC_GRAPPLE_USER					0.3

	CHARACTERISTIC_ITEMWEIGHTS					"fw_items.c"
	CHARACTERISTIC_AGGRESSION					0.7
	CHARACTERISTIC_SELFPRESERVATION				0.7
	CHARACTERISTIC_VENGEFULNESS					0.6

	CHARACTERISTIC_EASY_FRAGGER					0.1
	CHARACTERISTIC_ALERTNESS					0.05
	CHARACTERISTIC_SPRAYLOGO					"03_smile"
}

skill 5{
	CHARACTERISTIC_NAME							"Pelvis"
	CHARACTERISTIC_GENDER						"male"
	CHARACTERISTIC_ATTACK_SKILL					0.9
	CHARACTERISTIC_WEAPONWEIGHTS				"bots/pelvis_w.c"
	CHARACTERISTIC_AIM_SKILL					0.9
	CHARACTERISTIC_AIM_ACCURACY					0.9
	CHARACTERISTIC_VIEW_FACTOR					0.5
	CHARACTERISTIC_VIEW_MAXCHANGE				120
	CHARACTERISTIC_REACTIONTIME					0.5

	CHARACTERISTIC_CHAT_FILE					"bots/guys_t.c"
	CHARACTERISTIC_CHAT_NAME					"padman"
	CHARACTERISTIC_CHAT_CPM						225
	CHARACTERISTIC_CHAT_INSULT					0.8
	CHARACTERISTIC_CHAT_MISC					0.8
	CHARACTERISTIC_CHAT_STARTENDLEVEL			0.5
	CHARACTERISTIC_CHAT_ENTEREXITGAME			0.5
	CHARACTERISTIC_CHAT_KILL					0.5
	CHARACTERISTIC_CHAT_DEATH					0.5
	CHARACTERISTIC_CHAT_ENEMYSUICIDE			0.3
	CHARACTERISTIC_CHAT_HITTALKING				0.2
	CHARACTERISTIC_CHAT_HITNODEATH				0.8
	CHARACTERISTIC_CHAT_HITNOKILL				0.65
	CHARACTERISTIC_CHAT_RANDOM					0.7
	CHARACTERISTIC_CHAT_REPLY					0.5

	CHARACTERISTIC_CROUCHER						0.0
	CHARACTERISTIC_JUMPER						0.7
	CHARACTERISTIC_WALKER						0.000
	CHARACTERISTIC_WEAPONJUMPING				0.6
	CHARACTERISTIC_GRAPPLE_USER					0.55

	CHARACTERISTIC_ITEMWEIGHTS					"fw_items.c"
	CHARACTERISTIC_AGGRESSION					0.8
	CHARACTERISTIC_SELFPRESERVATION				0.9
	CHARACTERISTIC_VENGEFULNESS					0.7

	CHARACTERISTIC_EASY_FRAGGER					0.0
	CHARACTERISTIC_ALERTNESS					0.1
	CHARACTERISTIC_SPRAYLOGO					"03_smile"
}
